services:
  getter:
    build:
      context: .
      dockerfile: lite.Dockerfile
    image: getter:latest
    volumes:
      - ./:/app
    env_file:
      - config.env
    restart: on-failure
    network_mode: bridge
