version: "3.9"
services:
  getter:
    build: .
    image: getter:latest
    volumes:
      - ./:/app
    env_file:
      - config.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
